spring:
  datasource:
    url: jdbc:postgresql://db.xbecjsvpxtddriotykdw.supabase.co:5432/postgres
    username: postgres
    password: tharinda123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs.html
    operationsSorter: method
